server:
  port: 8010

spring:
  application:
    name: rabbitmq-provider
  rabbitmq:
    host: 192.168.31.58
    port: 5672
    username: guest
    password: guest
    #确认消息已发送到队列(Queue)
    publisher-returns: true
    #确认消息已发送到交换机(Exchange)
    publisher-confirm-type: correlated